language: c

os:
  - osx
  - linux

sudo: false

addons:
  apt:
    packages:
    - cvs
    - texinfo

compiler:
  - gcc

env:
  matrix:
    - TARGET_CPU=m68000
    - TARGET_CPU=m68020-60
    - TARGET_CPU=5475

before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update > /dev/null ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cvs ; fi'
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" == "gcc" ] ; then CC=gcc-4.9; fi'

script:
  - 'make download'
  - 'make ${TARGET_CPU}-skip-native OUT="> /dev/null"'
  # on osx it takes too long to build both cross and native toolchains
  - 'if [ "$TRAVIS_OS_NAME" != "osx" ];
     then
        unset CC CXX AR RANLIB LD;
        make ${TARGET_CPU}-native OUT="> /dev/null";
     fi'
