# default is xcode9.4 which doesn't contain any gcc preinstalled (https://travis-ci.community/t/gcc-cmake-versions-pre-installed-on-osx/4693)
# let's use latest xcode (so homebrew is happy) but with gcc-7 for speed reasons (gcc-4.9 is fast but too verbose)

language: c

matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && TARGET_CPU=m68000"
    - os: osx
      osx_image: xcode12.2
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && TARGET_CPU=m68020-60"
    - os: osx
      osx_image: xcode12.2
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && TARGET_CPU=5475"
    - os: linux
      env: MATRIX_EVAL="TARGET_CPU=m68000"
    - os: linux
      env: MATRIX_EVAL="TARGET_CPU=m68020-60"
    - os: linux
      env: MATRIX_EVAL="TARGET_CPU=5475"

addons:
  apt:
    packages:
      - texinfo
  homebrew:
    packages:
      - gcc@7
    update: false

compiler:
  - gcc

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make download
  - make ${TARGET_CPU}-skip-native OUT="> /dev/null"
  # on osx it takes too long to build both cross and native toolchains
  - 'if [ "$TRAVIS_OS_NAME" != "osx" ];
     then
       unset CC CXX AR RANLIB LD;
       make ${TARGET_CPU}-native OUT="> /dev/null";
     fi'
