# default is xcode9.4 which doesn't contain any gcc preinstalled (https://travis-ci.community/t/gcc-cmake-versions-pre-installed-on-osx/4693)
# let's use xcode10.3 which has gcc-9 (9.1.0) preinstalled

language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
      env: TARGET_CPU=m68000 CC=gcc-9 CXX=g++-9
    - os: osx
      osx_image: xcode10.3
      env: TARGET_CPU=m68020-60 CC=gcc-9 CXX=g++-9
    - os: osx
      osx_image: xcode10.3
      env: TARGET_CPU=5475 CC=gcc-9 CXX=g++-9
    - os: linux
      env: TARGET_CPU=m68000
    - os: linux
      env: TARGET_CPU=m68020-60
    - os: linux
      env: TARGET_CPU=5475

addons:
  apt:
    packages:
    - texinfo

compiler:
  - gcc

script:
  - make download
  - make ${TARGET_CPU}-skip-native OUT="> /dev/null"
  # on osx it takes too long to build both cross and native toolchains
  - 'if [ "$TRAVIS_OS_NAME" != "osx" ];
     then
       unset CC CXX AR RANLIB LD;
       make ${TARGET_CPU}-native OUT="> /dev/null";
     fi'
