# default is xcode9.4 which doesn't contain any gcc preinstalled (https://travis-ci.community/t/gcc-cmake-versions-pre-installed-on-osx/4693)
# gcc-4.9 is the only gcc fast enough to finish under 50 minutes on osx

language: c

os:
  - osx
  - linux

addons:
  apt:
    packages:
    - texinfo
  homebrew:
    packages:
    - gcc@7
    update: true

compiler:
  - gcc

env:
  matrix:
    - TARGET_CPU=m68000
    - TARGET_CPU=m68020-60
    - TARGET_CPU=5475

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" == "gcc" ]; then export CC=gcc-7; export CXX=g++-7; fi

script:
  - make download
  - make ${TARGET_CPU}-skip-native OUT="> /dev/null"
  # on osx it takes too long to build both cross and native toolchains
  - 'if [ "$TRAVIS_OS_NAME" != "osx" ];
     then
       unset CC CXX AR RANLIB LD;
       make ${TARGET_CPU}-native OUT="> /dev/null";
     fi'
